name: Deploy App on GKE cluster.
on:
  push:
    branches:
      - colpal-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print branch name
      #if: github.event_name == 'pull_request'
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: venkatarajv/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: us-central1-c
      with:
#         args: "cp dags/hello.py airflow-1600845150-web-79ddfc9b96-pslr4:/opt/airflow/dags -n=dev " 
        args: "chmod u+x ./deploy.sh && ./deploy.sh $BRANCH_NAME"
