name: Deploy App on GKE cluster.
on:
  push:
    branches:
      - colpal-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@colpal-dev
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@colpal-dev
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: us-central1-c
      with:
        args: apply -f packaging/k8s/manifests/ -n staging 
