name: sample workflow
on: 
  pull_request:
          branches: [ master ]
jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          docker-version: 19.03.12
      - run: docker -v 
      - run: docker images -a 
