name: sample workflow
on: 
  pull_request:
          branches: [ master ]
jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: zcong1993/setup-dockerize@v1.2.0
        with:
          dockerize-version: 19.03.12
      - run: docker -v 
      - run: docker images -a 
